### ISSUE TITLE
Add and refactor Unit-Tests

### ISSUE THREAD

**Issue by mKrswe** [nyadero/dreamwheels#1]
Hi @nyadero,
I saw your post on reddit and I can add/refactor some tests to get used to the Application.
If you agree, could you please help me to setup my local environment. In detail: How did you setup the authorisation when running the tests locally?

**Comment by nyadero** [comment]
Hi @mKrswe 
Thank you for the interest.I have updated the project in particular the GarageControllerTest class, detailing how to setup authorization for local tests. I hope it helps.

**Comment by mKrswe** [comment]
Hi @nyadero, I am still struggling a bit. When I run the GarageControllerTest the Test fails:
`Cannot invoke "org.springframework.security.core.userdetails.UserDetails.getUsername()" because "userDetails" is null`
This is the case because in the ApplicationConfig 
`return username -> {
    return authRepository.findByEmail(username).orElse(null);
};`
the user can not be found and null is returned.

**Comment by nyadero** [comment]
Hi @mKrswe,Have you managed to run the project on your machine by defining your own environment variables? If yes, then the error likely means that the user you are trying to authenticate in the test (with briannyadero@gmail.com as the email) is not found in the database or doesn’t meet the authentication requirements. In my case, it works as the user is registered and enabled on my local database.
To solve this:
1. Make sure that a user with the credentials you are using is saved in the database before running the test. or preferably create your own user with different email and password from mine.
 `
  @BeforeEach
    void generateJwtToken() {
        // Create a test user to generate the JWT
        // Make sure the user is enabled and also registered
        UserDetails testUser = new User("youremail@gmail.com", "yourpassword", Collections.emptyList());
        jwtToken = jwtUtils.generateJwtToken(testUser);
    }
`
2 .Ensure the user is enabled. You can enable the user by following the link that will be logged to the console after user registration is completed.
I hope this answers your question.
